// Regenerates src/lib/font-widths.ts: advance widths of the macOS system font at 14 pt (Raycast's list titles use
// the system font) for the characters My Day puts in its left date/time column, plus the Unicode spaces used to pad.
// Run: swift scripts/measure-font.swift > src/lib/font-widths.ts
import AppKit
let font = NSFont.systemFont(ofSize: 14)
func w(_ s: String) -> Double { Double((s as NSString).size(withAttributes: [.font: font]).width) }
var chars = Array("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz :–-.,'()/·").map(String.init)
chars += ["\u{00A0}", "\u{2007}", "\u{2008}", "\u{2009}", "\u{200A}", "\u{2002}", "\u{2003}", "\u{2004}", "\u{2005}", "\u{2006}"]
print("// Generated by scripts/measure-font.swift — system font (\(font.fontName)) at 14 pt, in points. Do not edit.")
print("export const FONT_SIZE = 14;")
print("export const WIDTHS: Record<string, number> = {")
for c in chars {
  let key = c.unicodeScalars.first!.value < 0x80 && c != "\\" && c != "\"" ? "\"\(c)\"" : String(format: "\"\\u%04X\"", c.unicodeScalars.first!.value)
  print("  \(key): \(String(format: "%.3f", w(c))),")
}
print("};")
